# Generated by Django 3.2.7 on 2021-09-06 06:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('chat', '0003_custom_user'),
    ]

    operations = [
        migrations.AlterField(
            model_name='custom',
            name='profile_pic',
            field=models.ImageField(blank=True, default='default.jpg', null=True, upload_to=''),
        ),
    ]
